const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const root = path.resolve(__dirname,'..'), window = {};
vm.runInNewContext(fs.readFileSync(path.join(root,'riobamba-conflictividad-data.js'),'utf8'),{window});
const d = window.RIOBAMBA_CONFLICTIVITY_CORRECTION;
const out = path.join(root,'data/seguridad-riobamba/correccion-conflictividad-20261001');
const table = (headers,rows) => `<div class="scroll"><table><thead><tr>${headers.map((h)=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map((r)=>`<tr>${r.map((v)=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const selected = ['URBANO','RURAL'].flatMap((scope)=>['DELINCUENCIA','VIOLENCIA','CONVIVENCIA'].map((category)=>({scope,category,...d.parameters[scope][category]})));
const image = (file,label) => `<figure><figcaption>${label}</figcaption><img src="${file}" alt="${label}" loading="lazy"></figure>`;
let html = `<!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Revision KDE y Gi* - Riobamba</title><style>body{font:14px Arial;margin:24px;color:#153042;background:#f5f8fa}main{max-width:1300px;margin:auto}h1{font-size:24px}h2{font-size:20px;margin-top:32px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(340px,1fr));gap:16px}figure{margin:0;background:white;padding:10px;border:1px solid #cbd5e1}img{width:100%;height:auto}figcaption{font-weight:bold;padding:8px}table{border-collapse:collapse;background:white;width:100%}th,td{padding:8px;border:1px solid #d9e1e6;text-align:left}.scroll{overflow:auto}p{line-height:1.5}a{color:#075985}</style><main><h1>Correccion metodologica - Revision local</h1><p>Datos reales; sin commit ni publicacion. Ambitos por cruce geometrico aprobado: 18 Plataformas y parroquias reales. No se fuerzan los conteos de la etiqueta parroquial.</p><h2>1. Diccionario y cinco clases</h2><a href="DICCIONARIO_APROBADO.csv">Diccionario exacto de subtipos</a>${table(['Categoria','Registros'],Object.entries(d.totals))}<h2>2. Ambitos operativos</h2>${table(['Ambito',...Object.keys(d.totals)],Object.entries(d.scopeCounts).map(([s,c])=>[s,...Object.keys(d.totals).map((name)=>c[name])]))}<p>850 registros SIN_ASIGNAR (820 dentro del canton, 30 fuera) no se incorporan por fuerza a urbano/rural. Mantienen sus coordenadas.</p><h2>3. Calidad de coordenadas y recurrencia</h2>${table(['Clase','Ambito','Eventos','XY unicas','% en XY repetida','Max. repeticion','Radio'],d.quality.map((q)=>[q.CATEGORIA,q.AMBITO,q.N_EVENTOS,q.N_COORD_UNICAS,q.PORCENTAJE_REGISTROS_EN_XY_REPETIDA.toFixed(2),q.MAX_REPETICION_XY,q.BANDWIDTH_RECOMENDADO]))}<p>Recurrencia global: 6.420 XY unicas; maximo 477. Se preservan todas las observaciones; no se deduplican, desplazan o ponderan por Emergencias. Repeticion no prueba error.</p><a href="BASE_ANALITICA_APROBADA.csv">Base derivada y flags de coordenadas</a><h2>4-9. Seis superficies KDE</h2><p>EPSG:32717; urbano 20 m, rural 100 m. Misma forma de kernel gaussiano truncado, normalizado a volumen 1; escala logaritmica fija compartida: 0 a ${d.colorReference.toFixed(2)} eventos/km2. Sin normalizacion automatica por mapa.</p><div class="grid">${selected.map((r)=>image(`KDE_${r.scope}_${r.category}_${r.bandwidth}.png`,`${r.scope} / ${r.category}: N=${r.records}, h=${r.bandwidth} m`)).join('')}</div><h2>10-11. Comparacion y recomendacion de bandwidth</h2><p>Validacion predictiva dejando fuera cada grupo XY completo; log-verosimilitud media con piso 1e-12/km2. Se elige el mayor puntaje, no el mejor aspecto visual. Todos los registros vuelven al raster final. Recomendaciones provisionales: rural 1.500 m queda en el limite superior ensayado y no demuestra optimalidad fuera del intervalo.</p>`;
for (const s of ['URBANO','RURAL']) for(const c of ['DELINCUENCIA','VIOLENCIA','CONVIVENCIA']) {
  const rows=d.evaluations.filter((r)=>r.scope===s && r.category===c);
  html+=`<h3>${s} / ${c}</h3>${table(['Radio','N','Puntaje CV','Sin soporte CV','Concentraciones','Umbral fijo','Area km2','Componentes soporte','Fusion vs. menor radio','Maximo eventos/km2','% recurrencia alta en pico','Recomendado'],rows.map((r)=>[r.bandwidth,r.records,r.cvMeanLogLikelihood.toFixed(4),r.heldOutLocationsWithoutSupport,r.concentrations,r.fixedConcentrationThreshold.toFixed(2),r.influenceAreaKm2.toFixed(3),r.supportComponents,r.supportComponentsMergedVsSmallest,r.maxDensityEventsKm2.toFixed(2),r.highRecurrenceShareAtMaximumPct.toFixed(1),r.recommended?'SI':'']))}<details><summary>Ver todos los candidatos</summary><div class="grid">${rows.map((r)=>image(`KDE_${s}_${c}_${r.bandwidth}.png`,`${s} / ${c}: ${r.bandwidth} m`)).join('')}</div></details>`;
}
html+=`<h2>Mapas Gi* recalculados</h2><div class="grid">${selected.map((r)=>image(`GI_${r.scope}_${r.category}.png`,`${r.scope} / ${r.category} - significancia nominal, sin FDR`)).join('')}</div>`;
html+=`<h2>Aportes al centro H-I-J-K</h2><p>${d.centralAudit.publishedExclusionDefinition} Bajo el nuevo diccionario, su aporte al KDE central anterior es ${d.centralAudit.institutionalContributionToPublishedCentralMassPctUnderNewDictionary.toFixed(4)}%. CORREGIDO_*_700 modifica solo la clasificacion; NUEVO cambia solo el radio. XY de frecuencia global >=10 define recurrencia alta; su aporte no demuestra error o causalidad.</p>${table(['Escenario','% masa central desde XY de alta recurrencia'],d.centralComparison.map((r)=>[r.ESCENARIO,r.PORCENTAJE_MASA_CENTRAL_XY_ALTA_REPETICION.toFixed(2)]))}<p>En el control de calidad, repeticion y coordenadas unicas corresponden a cada universo. Los flags de la base derivada utilizan la frecuencia global.</p>`;
html+=`<h2>12-13. Gi* urbano / rural</h2><p>Misma malla/vecindad: urbano 250/500 m; rural 1000/2000 m. Incluye celdas vacias y peso propio. Significancia nominal exploratoria, sin FDR. No se fuerzan coldspots.</p>${table(['Ambito','Categoria','N','H99','H95','H90','NS','C90','C95','C99'],selected.map((r)=>{const g=d.gi[r.scope][r.category];return [r.scope,r.category,g.records,...['HOTSPOT 99%','HOTSPOT 95%','HOTSPOT 90%','NO SIGNIFICATIVO','COLDSPOT 90%','COLDSPOT 95%','COLDSPOT 99%'].map((l)=>g.levels[l]||0)]}))}`;
html+=`<h2>14. Centro H-I-J-K antes / despues</h2><p>PUBLICADO reconstruye puntos y clasificacion anteriores a 700 m con unidades y escala comunes, no los pixeles del renderer antiguo. TODOS e INSTITUCIONAL son contrafactuales; RECLASIFICADO_INSTITUCIONAL identifica los registros antes violentos. Masa integrada no equivale a conteo absoluto del centro.</p>${table(['Escenario','N','Radio','Masa central','Max. central','Area influencia central'],d.centralComparison.map((r)=>[r.ESCENARIO,r.N_EVENTOS,r.BANDWIDTH,r.MASA_KDE_CENTRAL_HIJK.toFixed(2),r.MAX_DENSIDAD_CENTRAL.toFixed(2),r.AREA_INFLUENCIA_CENTRAL_KM2.toFixed(2)]))}<div class="grid">${d.centralComparison.map((r)=>image(`CENTRO_${r.ESCENARIO}.png`,r.ESCENARIO)).join('')}</div>`;
html+=`<h2>15-16. Controles y archivos</h2><p>Agregados dependientes de incidentes actualizados. Poblacion, geometria de cobertura de 31 camaras y accesibilidad poblacional/policial intactas. Originales y limites preservados.</p><p><a href="VALIDACION_CALCULOS.json">Validacion automatizada</a> | <a href="COMPARACION_BANDWIDTH.csv">33 evaluaciones</a> | <a href="COMPARACION_CENTRO_HIJK.csv">Comparacion central</a> | <a href="INFORME_FINAL.md">Informe y archivos modificados</a> | <a href="../../../visor-seguridad-riobamba-v2.html">Abrir visor local</a></p></main></html>`;
const mapFiles = [...d.evaluations.map((r)=>`KDE_${r.scope}_${r.category}_${r.bandwidth}.png`),
  ...selected.map((r)=>`GI_${r.scope}_${r.category}.png`), ...d.centralComparison.map((r)=>`CENTRO_${r.ESCENARIO}.png`)];
for (const file of mapFiles) if (!fs.existsSync(path.join(out,file))) throw new Error(`Missing calculated map: ${file}`);
html = html.replace('Correccion metodologica - Revision local', 'Correccion metodologica - Comparacion y validacion')
  .replace('Datos reales; sin commit ni publicacion.', 'Datos reales; publicacion autorizada el 1 de octubre de 2026.')
  .replace('Abrir visor local', 'Abrir visor');
fs.writeFileSync(path.join(out,'comparacion.html'),html);
console.log('Generated comparison: comparacion.html');
